### ISSUE TITLE
Something Missing?

### ISSUE THREAD

**Issue by rdafoe** [yriyazi/GearBox_Fault_detection-ICEE2024#1]
Very interesting project. Readme.md makes reference to /code folder and some .py files that don't appear to be in the repo. Are they available?

**Comment by yriyazi** [comment]
Hello, we have uploaded the project and only the missing dataset files, which you can find at https://www.kaggle.com/datasets/brjapon/gearbox-fault-diagnosis.

**Comment by rdafoe** [comment]
Hello, Thank you for responding. I did find the dataset files on kaggle but perhaps I'm not understanding something. The readme.md makes reference to  gearbox_fault_detection.py in /code folder that doesn't appear to be in the repo. Am I looking in right place?

**Comment by yriyazi** [comment]
You are right. The instructions were not clear. All the test and train codes were in the [ViT.ipynb](https://github.com/yriyazi/GearBox_Fault_detection-ICEE2024/blob/main/ViT.ipynb). I have added two other files.
